### ISSUE TITLE
New fork http://howtobuybitcoins.io/

### ISSUE THREAD

**Issue by howtobuybitcoins** [LUXSTACK/howtobuybitcoinsinfo-website#257]

**Comment by jonwaller** [comment]
Hey everyone,

We're working hard to roll out a new and upgraded site for howtobuybitcoins.info with a lot of new features and realtime data.

Rest assured, you can still contribute to the services.yaml file! These changes will be merged into the new site.

We're also including realtime feeds for exchange prices - if there's a public exchange price feed we don't have, let us know.

We're the original, and most high-traffic site for discovering how to buy bitcoins... and with the new version, howtobuybitcoins.info will continue to be the BEST PLACE to learn how to buy bitcoin... hold onto your hats!

Jonathan Waller
howtobuybitcoins.info

**Comment by howtobuybitcoins** [comment]
We've taken down howtobuybitcoins.io per Jon's request. Sorry for any confusion, if anyone thought we were trying to impersonate Jon, that was not the intention.

**Comment by hughht5** [comment]
@jonwaller how do we add a price ticker?

Quickbitcoin has an API for that at https://quickbitcoin.co.uk/ticker - sell rate shown is £ cost to buy 1 btc

Thanks
